# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  python_min: 3.11
  version: 0.3.11

package:
  name: gdptools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gdptools/gdptools-${{ version }}.tar.gz
  sha256: 9102f9ed2e23f90b16dc51771063d45ac555f858703837560dad0012e2c16b2e

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - gdptools = gdptools.__main__:main
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - click >=8.1,<9
    - bottleneck >=1.3.3
    - dask-geopandas >0.4.1
    - fastparquet >=2024.2
    - geopandas >=0.13.0
    - joblib >=1.4.0
    - netcdf4 >=1.5.8
    - numpy >2.0
    - pandas >=2.0.0
    - pyarrow >=10.0.0
    - pydantic >=2
    - pyproj >=3.7.2
    - pystac >=1.10
    - rasterio >=1.2.9
    - rioxarray >=0.15
    - s3fs >=2025.2.0
    - shapely >=2.0
    - statsmodels >=0.14
    - tqdm >=4.66.2
    - xarray >=2024.7.0
    - zarr >=2.12.0
    - urllib3 >=2.6.0
    - exactextract >=0.3.0
    - dask-core >2024.8.0
tests:
  - python:
      imports:
        - gdptools
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - nbclient
        - libgdal-hdf5
    script:
      - gdptools --help
      - pytest tests

about:
  summary: Tools for GeoData Portal polygon-to-polygon intersections.
  license: Unlicense
  license_file: LICENSE.md
  homepage: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
