# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.3.1"
  python_max_check: "3.13"

package:
  name: gdptools
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gdptools/gdptools-${{ version }}.tar.gz
  sha256: 7ed1c42cc1fd9efbfe5bfb6acc2e6b05e3e11a2fd70aba572ba5cc891ccf0729
  patches:
   - pyarrow_unpin.patch

build:
  number: 0
  noarch: python
  python:
    entry_points:
      - gdptools = gdptools.__main__:main
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
  run:
    - click >=8.1,<9
    - python >=${{ python_min }}
    - bottleneck >=1.3.3
    - dask >=2022.0.0
    - dask-core >2024.8.0
    - dask-geopandas >0.4.1
    - fastparquet >=2024.2,<=2024.5
    - geopandas >=0.13.0
    - geoviews >=1.12.0,<2.0.0
    - joblib >=1.4.0
    - metpy >=1.2.0
    - netcdf4 >=1.5.8
    - numpy >2.0
    - pandas >=2.0.0
    - pyarrow >=10.0.0
    - pydantic >=2
    - pydap >=3.2.2,<4.0.0
    - pyproj >=3.3.0
    - pystac >=1.10,<2.0
    - rasterio >=1.2.9,<1.5.0
    - rioxarray >=0.15,<0.16
    - s3fs >=2025.2.0,<2026.0.0
    - scipy >=1.13.0,<2.0.0
    - shapely >=2.0
    - statsmodels >=0.14,<1.0
    - tqdm >=4.66.2,<5.0.0
    # - urllib3 >=2.6.0
    - xarray >=2024.7.0,<2025.0.0
    - xpystac >=0.1.3,<0.2.0
    - zarr >=2.12.0
    - attrs >=20.3,<22
    - bump2version >=1.0.1,<2.0.0
    - certifi <2023.7.22
    # - pygeos >=0.14.0,<0.15.0
    # xarray[io]
    - cfgrib
    - cftime
    - fsspec
    - h5netcdf
    - pooch
    # xarray[accel]
    - flox

tests:
  - python:
      imports:
        - gdptools
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_max_check }}.*
  - files:
      source:
        - tests
    requirements:
      run:
        - pytest
        - nbclient
        - libgdal-hdf5
    script:
      - gdptools --help
      - pytest tests

about:
  summary: Tools for GeoData Portal polygon-to-polygon intersections.
  license: Unlicense
  license_file: LICENSE.md
  homepage: https://code.usgs.gov/wma/nhgf/toolsteam/gdptools

extra:
  recipe-maintainers:
    - rmcd-mscb
    - ocefpaf
